<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProjectBuilder.Application\ProjectBuilder.Application.csproj" />
    <ProjectReference Include="..\ProjectBuilder.Domain\ProjectBuilder.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\docs\schemas\project-builder-model.schema.json" Link="Portability\project-builder-model.schema.json" />
  </ItemGroup>

</Project>
