// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectBuilder.Infrastructure.Persistence;

#nullable disable

namespace ProjectBuilder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FoundationDbContext))]
    [Migration("20260816130954_AddCanvasViewLayouts")]
    partial class AddCanvasViewLayouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ActorPayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AuthorityJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ConstraintsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContextualRole")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("GoalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponsibilitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("actor_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.CanvasViewRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("LayoutVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Lens")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ModelRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Lens", "ScopeKey", "Visibility", "OwnerKey")
                        .IsUnique();

                    b.ToTable("canvas_views", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.CapabilityPayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutcomeIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ElementId");

                    b.ToTable("capability_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ClaimRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ElementIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("claims", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.EvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LimitationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ModelRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ProducedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("evidence", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.GapDispositionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Consequence")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("ReviewOn")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetMilestone")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ProfileId", "RuleCode", "ScopeId")
                        .IsUnique();

                    b.ToTable("gap_dispositions", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DefinitionStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentElementId");

                    b.HasIndex("ProjectId", "Order")
                        .IsUnique();

                    b.ToTable("model_elements", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelRelationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetElementId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceElementId");

                    b.HasIndex("TargetElementId");

                    b.HasIndex("Kind", "TargetElementId")
                        .IsUnique()
                        .HasDatabaseName("ux_model_relations_benefits_from_target")
                        .HasFilter("\"Kind\" = 'benefitsFrom'");

                    b.HasIndex("Kind", "SourceElementId", "TargetElementId")
                        .IsUnique();

                    b.ToTable("model_relations", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.NarrativePayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("narrative_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.OutcomePayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("SuccessSignalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("outcome_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.PathPayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("path_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.PortableProjectSnapshotRecord", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormatVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("ModelRevision")
                        .HasColumnType("bigint");

                    b.HasKey("ProjectId");

                    b.ToTable("portable_project_snapshots", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectChangeOperationRecord", b =>
                {
                    b.Property<Guid>("ChangeSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("ChangeSetId", "Sequence");

                    b.HasIndex("ProjectId", "ChangeSetId");

                    b.ToTable("project_change_operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_change_operations_sequence_nonnegative", "\"Sequence\" >= 0");
                        });
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectChangeSetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("BaseRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperationCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ResultRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("SemanticSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_change_sets", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_change_sets_operation_count_positive", "\"OperationCount\" > 0");
                        });
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("IntendedOutcome")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_workspace_normalized_name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.StateLogicPayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("state_logic_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.SystemContextPayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("system_context_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ActorPayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("Actor")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.ActorPayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.CanvasViewRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("CanvasViews")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.CapabilityPayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("Capability")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.CapabilityPayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ClaimRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("Claims")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.EvidenceRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ClaimRecord", "Claim")
                        .WithOne("Evidence")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.EvidenceRecord", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("Evidence")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.GapDispositionRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("GapDispositions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentElementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("Elements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelRelationRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("Relations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Source")
                        .WithMany()
                        .HasForeignKey("SourceElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Target")
                        .WithMany()
                        .HasForeignKey("TargetElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.NarrativePayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("Narrative")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.NarrativePayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.OutcomePayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("Outcome")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.OutcomePayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.PathPayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("Path")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.PathPayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.PortableProjectSnapshotRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithOne()
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.PortableProjectSnapshotRecord", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectChangeOperationRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectChangeSetRecord", "ChangeSet")
                        .WithMany("Operations")
                        .HasForeignKey("ChangeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeSet");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectChangeSetRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("ChangeSets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.StateLogicPayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("StateLogic")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.StateLogicPayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.SystemContextPayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("SystemContext")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.SystemContextPayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ClaimRecord", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", b =>
                {
                    b.Navigation("Actor");

                    b.Navigation("Capability");

                    b.Navigation("Children");

                    b.Navigation("Narrative");

                    b.Navigation("Outcome");

                    b.Navigation("Path");

                    b.Navigation("StateLogic");

                    b.Navigation("SystemContext");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectChangeSetRecord", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", b =>
                {
                    b.Navigation("CanvasViews");

                    b.Navigation("ChangeSets");

                    b.Navigation("Claims");

                    b.Navigation("Elements");

                    b.Navigation("Evidence");

                    b.Navigation("GapDispositions");

                    b.Navigation("Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
