// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectBuilder.Infrastructure.Persistence;

#nullable disable

namespace ProjectBuilder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FoundationDbContext))]
    [Migration("20260815204636_AddNarrativeHierarchy")]
    partial class AddNarrativeHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ActorPayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AuthorityJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ConstraintsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContextualRole")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("GoalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponsibilitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("actor_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DefinitionStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentElementId");

                    b.HasIndex("ProjectId", "Order")
                        .IsUnique();

                    b.ToTable("model_elements", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelRelationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetElementId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceElementId");

                    b.HasIndex("TargetElementId");

                    b.HasIndex("Kind", "SourceElementId", "TargetElementId")
                        .IsUnique();

                    b.ToTable("model_relations", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.NarrativePayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("narrative_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.OutcomePayloadRecord", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("SuccessSignalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ElementId");

                    b.ToTable("outcome_payloads", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectChangeSetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("BaseRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ResultRevision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_change_sets", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("IntendedOutcome")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_workspace_normalized_name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ActorPayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("Actor")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.ActorPayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentElementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("Elements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelRelationRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("Relations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Source")
                        .WithMany()
                        .HasForeignKey("SourceElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Target")
                        .WithMany()
                        .HasForeignKey("TargetElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.NarrativePayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("Narrative")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.NarrativePayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.OutcomePayloadRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", "Element")
                        .WithOne("Outcome")
                        .HasForeignKey("ProjectBuilder.Infrastructure.Persistence.OutcomePayloadRecord", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectChangeSetRecord", b =>
                {
                    b.HasOne("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", "Project")
                        .WithMany("ChangeSets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ModelElementRecord", b =>
                {
                    b.Navigation("Actor");

                    b.Navigation("Children");

                    b.Navigation("Narrative");

                    b.Navigation("Outcome");
                });

            modelBuilder.Entity("ProjectBuilder.Infrastructure.Persistence.ProjectRecord", b =>
                {
                    b.Navigation("ChangeSets");

                    b.Navigation("Elements");

                    b.Navigation("Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
